[theme]
# Primary accent color for interactive elements
# primaryColor = "#d33682"

# Background color for the main content area
# backgroundColor = "#F1F2F2"

# Background color used for the sidebar and most interative widgets
# secondaryBackgroundColor = "#586e75"

# Color used for almost all text
# textColor = "#000000"


[client]
toolbarMode = "minimal"