"""README.md generation for replication packages."""

from __future__ import annotations

from datetime import date

from datasure.processing.replication.script_generators import LANGUAGE_EXT

_LANG_DISPLAY = {"stata": "Stata", "r": "R", "python": "Python"}


def _run_instructions(lang: str, safe_project: str, safe_survey: str) -> str:
    ext = LANGUAGE_EXT[lang]

    if lang == "stata":
        return (
            "1. Open Stata.\n"
            "2. Open `scripts/master.do`.\n"
            "3. Update the `global root` path near the top of the file\n"
            "   to point to the parent folder of this replication package.\n"
            "4. Run from the Stata command window:\n"
            f"   `do master.{ext}`\n"
            "5. The prepped and corrected datasets will appear in `output/`."
        )

    if lang == "r":
        return (
            "1. Open R or RStudio.\n"
            "2. Open `scripts/master.R`.\n"
            "3. Update `root_dir` near the top of the file\n"
            "   to point to the parent folder of this replication package.\n"
            "4. Run the script:\n"
            f'   `source("scripts/master.{ext}")`\n'
            "5. The prepped and corrected datasets will appear in `output/`.\n\n"
            "**Required packages:** `readr`\n"
            'Install with: `install.packages("readr")`'
        )

    # python
    return (
        "1. Open a terminal and navigate to this package folder.\n"
        "2. Open `scripts/master.py`.\n"
        "3. Update `ROOT_DIR` near the top of the file\n"
        "   to point to the parent folder of this replication package.\n"
        "4. Run the script:\n"
        "   `python scripts/master.py`\n"
        "5. The prepped and corrected datasets will appear in `output/`.\n\n"
        "**Required packages:** `pandas`\n"
        "Install with: `pip install pandas`"
    )


def generate_readme(
    project_name: str,
    survey_name: str,
    lang: str,
    datasure_version: str,
    correction_count: int,
    prep_count: int,
    raw_rows: int,
    prepped_rows: int,
    corrected_rows: int,
    n_corrections_by_action: dict[str, int],
) -> str:
    """Generate a README.md string for the replication package.

    Parameters
    ----------
    project_name : str
        Human-readable project name.
    survey_name : str
        Human-readable survey name.
    lang : str
        Export language: 'stata', 'r', or 'python'.
    datasure_version : str
        Version of DataSure that generated this package.
    correction_count : int
        Total number of correction log entries.
    prep_count : int
        Total number of preparation steps recorded.
    raw_rows : int
        Row count of the raw dataset.
    prepped_rows : int
        Row count of the prepped dataset.
    corrected_rows : int
        Row count of the corrected dataset.
    n_corrections_by_action : dict[str, int]
        Count of corrections keyed by action type.

    Returns
    -------
    str
        README.md content as a string.
    """
    today = date.today().isoformat()
    safe_survey = survey_name.lower().replace(" ", "_")
    safe_project = project_name.lower().replace(" ", "_")
    ext = LANGUAGE_EXT[lang]
    lang_display = _LANG_DISPLAY[lang]

    run_instructions = _run_instructions(lang, safe_project, safe_survey)

    if n_corrections_by_action:
        action_rows = "\n".join(
            f"| {action} | {count} |"
            for action, count in sorted(n_corrections_by_action.items())
        )
    else:
        action_rows = "| — | 0 |"

    lines = [
        f"# {project_name} — Replication Package",
        "",
        f"**Survey:** {survey_name}  ",
        f"**Generated by:** DataSure {datasure_version}  ",
        f"**Date:** {today}  ",
        f"**Language:** {lang_display}  ",
        "",
        "---",
        "",
        "## Overview",
        "",
        "This replication package contains the raw survey dataset, all data",
        "preparation and correction scripts, and the output datasets. Running",
        "the master script will reproduce the prepped and corrected datasets",
        "from the raw source.",
        "",
        "---",
        "",
        "## Folder structure",
        "",
        "```",
        f"{safe_project}_replication/",
        "├── raw/",
        f"│   └── {safe_survey}_raw.csv          # Unmodified source dataset",
        "├── scripts/",
        f"│   ├── master.{ext:<6}               # Entry point — run this",
        f"│   ├── prepare_data.{ext:<3}          # All recorded prep steps",
        f"│   └── corrections.{ext:<3}           # All recorded corrections",
        "├── output/",
        f"│   ├── {safe_survey}_prepped.csv      # Dataset after prep steps",
        f"│   └── {safe_survey}_corrected.csv    # Final corrected dataset",
        "└── docs/",
        "    ├── README.md                       # This file",
        "    ├── codebook.csv                    # Variable-level metadata",
        "    ├── correction_log.csv              # Full correction audit trail",
        "    └── prep_log.csv                    # Full preparation audit trail",
        "```",
        "",
        "---",
        "",
        "## How to run",
        "",
        run_instructions,
        "",
        "---",
        "",
        "## Data pipeline summary",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Raw dataset rows | {raw_rows:,} |",
        f"| Preparation steps applied | {prep_count:,} |",
        f"| Prepped dataset rows | {prepped_rows:,} |",
        f"| Corrections applied | {correction_count:,} |",
        f"| Corrected dataset rows | {corrected_rows:,} |",
        "",
        "**Corrections by action type:**",
        "",
        "| Action | Count |",
        "|--------|-------|",
        action_rows,
        "",
        "---",
        "",
        "## File reference",
        "",
        "| File | Description |",
        "|------|-------------|",
        f"| `raw/{safe_survey}_raw.csv` | Original unmodified dataset |",
        f"| `scripts/master.{ext}` | Master script — start here |",
        f"| `scripts/prepare_data.{ext}` | Data preparation steps |",
        f"| `scripts/corrections.{ext}` | All data corrections |",
        f"| `output/{safe_survey}_prepped.csv` | Dataset after prep steps |",
        f"| `output/{safe_survey}_corrected.csv` | Final corrected dataset |",
        "| `docs/codebook.csv` | Variable metadata |",
        "| `docs/correction_log.csv` | Full correction audit trail |",
        "| `docs/prep_log.csv` | Full preparation audit trail |",
    ]

    return "\n".join(lines) + "\n"
