"""README.md generation for Stata replication packages."""

from __future__ import annotations

from datetime import date


def generate_readme(
    project_name: str,
    survey_name: str,
    datasure_version: str,
    correction_count: int,
    prep_count: int,
    raw_rows: int,
    prepped_rows: int,
    corrected_rows: int,
    n_corrections_by_action: dict[str, int],
) -> str:
    """Generate a README.md string for the Stata replication package.

    Parameters
    ----------
    project_name : str
        Human-readable project name.
    survey_name : str
        Human-readable survey name.
    datasure_version : str
        Version of DataSure that generated this package.
    correction_count : int
        Total number of correction log entries.
    prep_count : int
        Total number of preparation steps recorded.
    raw_rows : int
        Row count of the raw dataset.
    prepped_rows : int
        Row count of the prepped dataset.
    corrected_rows : int
        Row count of the corrected dataset.
    n_corrections_by_action : dict[str, int]
        Count of corrections keyed by action type.

    Returns
    -------
    str
        README.md content as a string.
    """
    today = date.today().isoformat()
    safe_survey = survey_name.lower().replace(" ", "_")
    safe_project = project_name.lower().replace(" ", "_")

    if n_corrections_by_action:
        action_rows = "\n".join(
            f"| {action} | {count} |"
            for action, count in sorted(n_corrections_by_action.items())
        )
    else:
        action_rows = "| — | 0 |"

    lines = [
        f"# {project_name} — Replication Package",
        "",
        f"**Survey:** {survey_name}  ",
        f"**Generated by:** DataSure {datasure_version}  ",
        f"**Date:** {today}  ",
        "**Language:** Stata  ",
        "",
        "---",
        "",
        "## Overview",
        "",
        "This replication package contains the raw survey dataset, all data",
        "preparation and correction do-files, and audit logs. Running the",
        "master script will reproduce the prepped and corrected datasets",
        "from the raw source and generate the variable codebook.",
        "",
        "---",
        "",
        "## Folder structure",
        "",
        "```",
        f"{safe_project}_replication/",
        "├── raw/",
        f"│   └── {safe_survey}_raw.csv          # Unmodified source dataset (CSV)",
        "├── scripts/",
        "│   ├── master.do                       # Entry point — run this",
        "│   ├── import_data.do                  # Import CSV and save as DTA",
        "│   ├── prepare_data.do                 # All recorded prep steps",
        "│   └── corrections.do                  # All recorded corrections",
        "├── output/                             # Created when scripts are run",
        f"│   ├── {safe_survey}_raw.dta          # Raw Stata dataset",
        f"│   ├── {safe_survey}_prepped.dta      # Dataset after prep steps",
        f"│   └── {safe_survey}_corrected.dta    # Final corrected dataset",
        "└── docs/",
        "    ├── README.md                       # This file",
        "    ├── codebook.xlsx                   # Codebook (generated by ipacodebook)",
        "    ├── correction_log.csv              # Full correction audit trail",
        "    └── prep_log.csv                    # Full preparation audit trail",
        "```",
        "",
        "---",
        "",
        "## How to run",
        "",
        "1. Install **ipaclean** (required for codebook generation) from the",
        "   Stata command window:",
        "   ```stata",
        '   net install ipaclean, from("https://raw.githubusercontent.com/PovertyAction/ipaclean/main/src") replace',
        "   ```",
        "2. Open `scripts/master.do`.",
        "3. Update the `global root` path near the top of the file to point",
        "   to the parent folder of this replication package:",
        "   ```stata",
        '   global root "C:/path/to/parent/folder"',
        "   ```",
        "4. Run from the Stata command window:",
        "   ```stata",
        "   do master.do",
        "   ```",
        "5. The prepped and corrected datasets (`.dta`) will appear in `output/`.",
        "6. The codebook (`codebook.xlsx`) will appear in `docs/`.",
        "",
        "---",
        "",
        "## Data pipeline summary",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Raw dataset rows | {raw_rows:,} |",
        f"| Preparation steps applied | {prep_count:,} |",
        f"| Prepped dataset rows | {prepped_rows:,} |",
        f"| Corrections applied | {correction_count:,} |",
        f"| Corrected dataset rows | {corrected_rows:,} |",
        "",
        "**Corrections by action type:**",
        "",
        "| Action | Count |",
        "|--------|-------|",
        action_rows,
        "",
        "---",
        "",
        "## File reference",
        "",
        "| File | Description |",
        "|------|-------------|",
        f"| `raw/{safe_survey}_raw.csv` | Original unmodified dataset |",
        "| `scripts/master.do` | Master script — start here |",
        "| `scripts/import_data.do` | Imports CSV and saves as DTA |",
        "| `scripts/prepare_data.do` | Data preparation steps |",
        "| `scripts/corrections.do` | All data corrections |",
        f"| `output/{safe_survey}_raw.dta` | Raw Stata dataset (generated) |",
        f"| `output/{safe_survey}_prepped.dta` | Dataset after prep steps (generated) |",
        f"| `output/{safe_survey}_corrected.dta` | Final corrected dataset (generated) |",
        "| `docs/codebook.xlsx` | Variable codebook (generated by ipacodebook) |",
        "| `docs/correction_log.csv` | Full correction audit trail |",
        "| `docs/prep_log.csv` | Full preparation audit trail |",
    ]

    return "\n".join(lines) + "\n"
