"""Stata script generators for replication packages."""

from __future__ import annotations

from datetime import date

import polars as pl

SCRIPT_EXT = "do"
_C = "*"  # Stata comment character


def _header(
    title: str,
    project_name: str,
    survey_name: str,
    datasure_version: str,
) -> str:
    today = date.today().isoformat()
    sep = "=" * 60
    return "\n".join(
        [
            f"{_C} {sep}",
            f"{_C} {title}",
            f"{_C} Project: {project_name}",
            f"{_C} Survey:  {survey_name}",
            f"{_C} Generated by DataSure {datasure_version} on {today}",
            f"{_C} {sep}",
            "",
        ]
    )


def _escape(value: str) -> str:
    """Escape double quotes in a Stata string literal."""
    return value.replace('"', '""')


def _is_numeric(value: str) -> bool:
    try:
        float(value)
    except (ValueError, TypeError):
        return False
    else:
        return True


def _emit_stata(
    action: str,
    key_col: str,
    key_val: str,
    col: str | None,
    new_val: str | None,
    reason: str,
) -> list[str]:
    comment = f"{_C} {action}: {key_col}=={key_val!r}"
    if col:
        comment += f" | {col}"
    if reason:
        comment += f" | {reason}"

    escaped_key = _escape(key_val)

    if action == "modify value" and col and new_val is not None:
        if _is_numeric(new_val):
            stmt = f'replace {col} = {new_val} if {key_col} == "{escaped_key}"'
        else:
            escaped_val = _escape(new_val)
            stmt = f'replace {col} = "{escaped_val}" if {key_col} == "{escaped_key}"'
    elif action == "remove value" and col:
        stmt = f'replace {col} = . if {key_col} == "{escaped_key}"'
    elif action == "remove row":
        stmt = f'drop if {key_col} == "{escaped_key}"'
    else:
        return []

    return [comment, stmt, ""]


def generate_corrections_script(
    correction_log: pl.DataFrame,
    key_col: str,
    project_name: str,
    survey_name: str,
    datasure_version: str,
) -> str:
    """Generate a Stata corrections script from the correction log.

    Parameters
    ----------
    correction_log : pl.DataFrame
        Correction log with columns: action, KEY, column, new_value, reason.
    key_col : str
        The survey key column name.
    project_name : str
        Human-readable project name.
    survey_name : str
        Human-readable survey name.
    datasure_version : str
        Version of DataSure that generated this package.

    Returns
    -------
    str
        Stata script content as a string.
    """
    header = _header("Corrections Script", project_name, survey_name, datasure_version)

    if correction_log.is_empty():
        return header + f"{_C} No corrections recorded.\n"

    lines: list[str] = [header]

    for row in correction_log.iter_rows(named=True):
        action = str(row["action"])
        key_val = str(row["KEY"])
        col = row.get("column")
        new_val = row.get("new_value")
        reason = str(row.get("reason") or "")
        lines += _emit_stata(action, key_col, key_val, col, new_val, reason)

    return "\n".join(lines)


def generate_master_script(
    project_name: str,
    survey_name: str,
    datasure_version: str,
) -> str:
    """Generate the Stata master replication script.

    Parameters
    ----------
    project_name : str
        Human-readable project name.
    survey_name : str
        Human-readable survey name.
    datasure_version : str
        Version of DataSure.

    Returns
    -------
    str
        Stata script content as a string.
    """
    header = _header(
        "Master Replication Script",
        project_name,
        survey_name,
        datasure_version,
    )
    safe_survey = survey_name.lower().replace(" ", "_")
    safe_project = project_name.lower().replace(" ", "_")

    lines = [
        header,
        "* -------------------------------------------------------",
        "* INSTRUCTIONS:",
        "* 1. Install ipaclean (required for codebook generation):",
        "*    net install ipaclean, \\",
        '*      from("https://raw.githubusercontent.com/PovertyAction/ipaclean/main/src") \\',
        "*      replace",
        "* 2. Set `root` below to the full path of the parent folder",
        f"*    that contains the {safe_project}_replication/ directory.",
        "*    Example:  global root C:/Users/you/Desktop",
        "* 3. Run this script from the Stata command window:",
        "*    do master.do",
        "* -------------------------------------------------------",
        "",
        'global root    "REPLACE_WITH_PARENT_PATH"',
        f'global pkg     "$root/{safe_project}_replication"',
        'global raw     "$pkg/raw"',
        'global scripts "$pkg/scripts"',
        'global output  "$pkg/output"',
        'global docs    "$pkg/docs"',
        "",
        "* Step 1: Import raw CSV and save as Stata dataset",
        'do "$scripts/import_data.do"',
        "",
        "* Step 2: Apply preparation steps",
        f'use "$raw/{safe_survey}_raw.dta", clear',
        'do "$scripts/prepare_data.do"',
        "",
        "* Save prepped dataset",
        f'save "$output/{safe_survey}_prepped.dta", replace',
        "",
        "* Step 3: Apply all recorded corrections",
        'do "$scripts/corrections.do"',
        "",
        "* Save corrected dataset",
        f'save "$output/{safe_survey}_corrected.dta", replace',
        "",
        "* Step 4: Generate codebook (requires ipaclean)",
        'ipacodebook using "$docs/codebook.xlsx", replace',
        "",
        'display "Done. Output files saved to output/ and docs/."',
    ]

    return "\n".join(lines) + "\n"


def generate_import_script(
    project_name: str,
    survey_name: str,
    datasure_version: str,
) -> str:
    """Generate a Stata import script that loads the raw CSV and saves as DTA.

    Parameters
    ----------
    project_name : str
        Human-readable project name.
    survey_name : str
        Human-readable survey name.
    datasure_version : str
        Version of DataSure.

    Returns
    -------
    str
        Stata script content as a string.
    """
    header = _header("Import Script", project_name, survey_name, datasure_version)
    safe_survey = survey_name.lower().replace(" ", "_")

    lines = [
        header,
        "* Import raw CSV dataset (all columns as strings to preserve data as-is)",
        f'import delimited "$raw/{safe_survey}_raw.csv", stringcols(_all) clear',
        "",
        "* Save as Stata dataset",
        f'save "$raw/{safe_survey}_raw.dta", replace',
        "",
        'display "Raw dataset imported and saved as DTA."',
    ]
    return "\n".join(lines) + "\n"
