"""Stata, R, and Python script generators for replication packages."""

from __future__ import annotations

from datetime import date

import polars as pl

LANGUAGE_EXT: dict[str, str] = {"stata": "do", "r": "R", "python": "py"}
_COMMENT: dict[str, str] = {"stata": "*", "r": "#", "python": "#"}


def _header(
    lang: str,
    title: str,
    project_name: str,
    survey_name: str,
    datasure_version: str,
) -> str:
    c = _COMMENT[lang]
    today = date.today().isoformat()
    sep = "=" * 60
    return "\n".join(
        [
            f"{c} {sep}",
            f"{c} {title}",
            f"{c} Project: {project_name}",
            f"{c} Survey:  {survey_name}",
            f"{c} Generated by DataSure {datasure_version} on {today}",
            f"{c} {sep}",
            "",
        ]
    )


def _escape(value: str, lang: str) -> str:
    """Escape special characters in a string literal for the target language."""
    if lang == "stata":
        return value.replace('"', '""')
    return value.replace("'", "\\'")


def _is_numeric(value: str) -> bool:
    try:
        float(value)
    except (ValueError, TypeError):
        return False
    else:
        return True


def _emit_stata(
    action: str,
    key_col: str,
    key_val: str,
    col: str | None,
    new_val: str | None,
    reason: str,
) -> list[str]:
    c = "*"
    comment = f"{c} {action}: {key_col}=={key_val!r}"
    if col:
        comment += f" | {col}"
    if reason:
        comment += f" | {reason}"

    escaped_key = _escape(key_val, "stata")

    if action == "modify value" and col and new_val is not None:
        if _is_numeric(new_val):
            stmt = f'replace {col} = {new_val} if {key_col} == "{escaped_key}"'
        else:
            escaped_val = _escape(new_val, "stata")
            stmt = f'replace {col} = "{escaped_val}" if {key_col} == "{escaped_key}"'
    elif action == "remove value" and col:
        stmt = f'replace {col} = . if {key_col} == "{escaped_key}"'
    elif action == "remove row":
        stmt = f'drop if {key_col} == "{escaped_key}"'
    else:
        return []

    return [comment, stmt, ""]


def _emit_r(
    action: str,
    key_col: str,
    key_val: str,
    col: str | None,
    new_val: str | None,
    reason: str,
) -> list[str]:
    indent = "  "
    c = "#"
    comment = f"{indent}{c} {action}: {key_col}=={key_val!r}"
    if col:
        comment += f" | {col}"
    if reason:
        comment += f" | {reason}"

    escaped_key = _escape(key_val, "r")

    if action == "modify value" and col and new_val is not None:
        if _is_numeric(new_val):
            stmt = f'{indent}df[df${key_col} == "{escaped_key}", "{col}"] <- {new_val}'
        else:
            escaped_val = _escape(new_val, "r")
            stmt = (
                f'{indent}df[df${key_col} == "{escaped_key}", "{col}"]'
                f' <- "{escaped_val}"'
            )
    elif action == "remove value" and col:
        stmt = f'{indent}df[df${key_col} == "{escaped_key}", "{col}"] <- NA'
    elif action == "remove row":
        stmt = f'{indent}df <- df[df${key_col} != "{escaped_key}", ]'
    else:
        return []

    return [comment, stmt, ""]


def _emit_python(
    action: str,
    key_col: str,
    key_val: str,
    col: str | None,
    new_val: str | None,
    reason: str,
) -> list[str]:
    indent = "    "
    c = "#"
    comment = f"{indent}{c} {action}: {key_col}=={key_val!r}"
    if col:
        comment += f" | {col}"
    if reason:
        comment += f" | {reason}"

    escaped_key = _escape(key_val, "python")

    if action == "modify value" and col and new_val is not None:
        if _is_numeric(new_val):
            stmt = (
                f"{indent}df.loc["
                f"df['{key_col}'] == '{escaped_key}', '{col}'] = {new_val}"
            )
        else:
            escaped_val = _escape(new_val, "python")
            stmt = (
                f"{indent}df.loc["
                f"df['{key_col}'] == '{escaped_key}', '{col}'] = '{escaped_val}'"
            )
    elif action == "remove value" and col:
        stmt = f"{indent}df.loc[df['{key_col}'] == '{escaped_key}', '{col}'] = None"
    elif action == "remove row":
        stmt = (
            f"{indent}df = df["
            f"df['{key_col}'] != '{escaped_key}'].reset_index(drop=True)"
        )
    else:
        return []

    return [comment, stmt, ""]


def generate_corrections_script(
    lang: str,
    correction_log: pl.DataFrame,
    key_col: str,
    project_name: str,
    survey_name: str,
    datasure_version: str,
) -> str:
    """Generate a corrections script from the correction log.

    Parameters
    ----------
    lang : str
        Target language: 'stata', 'r', or 'python'.
    correction_log : pl.DataFrame
        Correction log with columns: action, KEY, column, new_value, reason.
    key_col : str
        The survey key column name.
    project_name : str
        Human-readable project name.
    survey_name : str
        Human-readable survey name.
    datasure_version : str
        Version of DataSure that generated this package.

    Returns
    -------
    str
        Script content as a string.
    """
    header = _header(
        lang, "Corrections Script", project_name, survey_name, datasure_version
    )
    c = _COMMENT[lang]

    if correction_log.is_empty():
        return header + f"{c} No corrections recorded.\n"

    lines: list[str] = [header]

    if lang == "python":
        lines += [
            "import pandas as pd  # noqa: F401",
            "",
            "",
            "def apply_corrections(df: 'pd.DataFrame') -> 'pd.DataFrame':",
            '    """Apply all recorded corrections. Returns a corrected copy."""',
            "    df = df.copy()",
            "",
        ]
    elif lang == "r":
        lines += [
            "apply_corrections <- function(df) {",
            "",
        ]

    for row in correction_log.iter_rows(named=True):
        action = str(row["action"])
        key_val = str(row["KEY"])
        col = row.get("column")
        new_val = row.get("new_value")
        reason = str(row.get("reason") or "")

        if lang == "stata":
            lines += _emit_stata(action, key_col, key_val, col, new_val, reason)
        elif lang == "r":
            lines += _emit_r(action, key_col, key_val, col, new_val, reason)
        else:
            lines += _emit_python(action, key_col, key_val, col, new_val, reason)

    if lang == "python":
        lines += ["    return df", ""]
    elif lang == "r":
        lines += ["  return(df)", "}", ""]

    return "\n".join(lines)


def generate_master_script(
    lang: str,
    project_name: str,
    survey_name: str,
    datasure_version: str,
) -> str:
    """Generate the master replication script.

    Parameters
    ----------
    lang : str
        Target language: 'stata', 'r', or 'python'.
    project_name : str
        Human-readable project name.
    survey_name : str
        Human-readable survey name.
    datasure_version : str
        Version of DataSure.

    Returns
    -------
    str
        Script content as a string.
    """
    header = _header(
        lang,
        "Master Replication Script",
        project_name,
        survey_name,
        datasure_version,
    )
    safe_survey = survey_name.lower().replace(" ", "_")
    safe_project = project_name.lower().replace(" ", "_")
    ext = LANGUAGE_EXT[lang]

    if lang == "stata":
        lines = [
            header,
            "* -------------------------------------------------------",
            "* INSTRUCTIONS:",
            "* 1. Set `root` below to the full path of the parent folder",
            f"*    that contains the {safe_project}_replication/ directory.",
            "*    Example:  global root C:/Users/you/Desktop",
            "* 2. Run this script from the Stata command window:",
            f"*    do master.{ext}",
            "* -------------------------------------------------------",
            "",
            'global root    "REPLACE_WITH_PARENT_PATH"',
            f'global pkg     "$root/{safe_project}_replication"',
            'global raw     "$pkg/raw"',
            'global scripts "$pkg/scripts"',
            'global output  "$pkg/output"',
            "",
            "* Load raw dataset",
            f'import delimited "$raw/{safe_survey}_raw.csv", stringcols(_all) clear',
            "",
            "* Apply preparation steps",
            f'do "$scripts/prepare_data.{ext}"',
            "",
            "* Save prepped dataset",
            f'export delimited "$output/{safe_survey}_prepped.csv", replace',
            "",
            "* Apply all recorded corrections",
            f'do "$scripts/corrections.{ext}"',
            "",
            "* Save corrected dataset",
            f'export delimited "$output/{safe_survey}_corrected.csv", replace',
            "",
            'display "Done. Corrected dataset saved to output/."',
        ]

    elif lang == "r":
        lines = [
            header,
            "library(readr)",
            "",
            "# -------------------------------------------------------",
            "# INSTRUCTIONS:",
            "# 1. Set root_dir below to the full path of the parent folder",
            f"#    that contains the {safe_project}_replication/ directory.",
            '#    Example:  root_dir <- "C:/Users/you/Desktop"',
            "# 2. Run this script:",
            f'#    source("scripts/master.{ext}")',
            "# -------------------------------------------------------",
            "",
            'root_dir <- "REPLACE_WITH_PARENT_PATH"',
            f'pkg_dir  <- file.path(root_dir, "{safe_project}_replication")',
            "",
            "# Load prepare_data and corrections functions",
            f'source(file.path(pkg_dir, "scripts", "prepare_data.{ext}"))',
            f'source(file.path(pkg_dir, "scripts", "corrections.{ext}"))',
            "",
            "# Load raw dataset",
            "df <- read_csv(",
            f'  file.path(pkg_dir, "raw", "{safe_survey}_raw.csv")',
            ")",
            "",
            "# Apply preparation steps",
            "df <- prepare_data(df)",
            "",
            "# Save prepped dataset",
            "write_csv(",
            "  df,",
            f'  file.path(pkg_dir, "output", "{safe_survey}_prepped.csv")',
            ")",
            "",
            "# Apply all recorded corrections",
            "df <- apply_corrections(df)",
            "",
            "# Save corrected dataset",
            "write_csv(",
            "  df,",
            f'  file.path(pkg_dir, "output", "{safe_survey}_corrected.csv")',
            ")",
            "",
            'cat("Done. Corrected dataset saved to output/.\\n")',
        ]

    else:  # python
        lines = [
            header,
            "import os",
            "import sys",
            "",
            "import pandas as pd",
            "",
            "# -------------------------------------------------------",
            "# INSTRUCTIONS:",
            "# 1. Set ROOT_DIR below to the full path of the parent folder",
            f"#    that contains the {safe_project}_replication/ directory.",
            '#    Windows example:  ROOT_DIR = r"C:\\Users\\you\\Desktop"',
            '#    Mac/Linux example: ROOT_DIR = "/home/you/Desktop"',
            "# 2. Run this script:",
            "#    python scripts/master.py",
            "# -------------------------------------------------------",
            "",
            'ROOT_DIR = r"REPLACE_WITH_PARENT_PATH"',
            f'PKG_DIR = os.path.join(ROOT_DIR, "{safe_project}_replication")',
            "",
            "# Make the scripts modules importable",
            'sys.path.insert(0, os.path.join(PKG_DIR, "scripts"))',
            "import prepare_data as _prep  # type: ignore",
            "import corrections  # type: ignore",
            "",
            "# Load raw dataset",
            "df = pd.read_csv(",
            f'    os.path.join(PKG_DIR, "raw", "{safe_survey}_raw.csv")',
            ")",
            "",
            "# Apply preparation steps",
            "df = _prep.prepare_data(df)",
            "",
            "# Save prepped dataset",
            "prep_path = os.path.join(",
            f'    PKG_DIR, "output", "{safe_survey}_prepped.csv"',
            ")",
            "df.to_csv(prep_path, index=False)",
            "",
            "# Apply all recorded corrections",
            "df = corrections.apply_corrections(df)",
            "",
            "# Save corrected dataset",
            "out_path = os.path.join(",
            f'    PKG_DIR, "output", "{safe_survey}_corrected.csv"',
            ")",
            "df.to_csv(out_path, index=False)",
            'print(f"Done. Corrected dataset saved to {out_path}")',
        ]

    return "\n".join(lines) + "\n"
