"""data-dict.yaml generation from a Polars DataFrame.

Emits a data dictionary compliant with the data-dict.yaml specification
(https://data-dict.tidyverse.org/spec.html), describing one table backed by
a Parquet file.
"""

from __future__ import annotations

from datetime import date

import polars as pl
import yaml

_SPEC_VERSION = "0.1.0"
_LEARN_MORE = "https://data-dict.tidyverse.org/"

# Low-cardinality text columns are described with an explicit `values` list
# instead of `range`/`examples`.
_ENUM_MAX_UNIQUE = 20

_NUMERIC_DTYPES = (
    pl.Int8,
    pl.Int16,
    pl.Int32,
    pl.Int64,
    pl.UInt8,
    pl.UInt16,
    pl.UInt32,
    pl.UInt64,
    pl.Float32,
    pl.Float64,
)


def _column_type(dtype: pl.DataType) -> str:
    if dtype in _NUMERIC_DTYPES:
        return "number"
    if dtype == pl.Boolean:
        return "boolean"
    if dtype == pl.Date:
        return "date"
    if isinstance(dtype, pl.Datetime):
        return "datetime"
    return "string"


def _sample_values(series: pl.Series, limit: int) -> list:
    non_null = series.drop_nulls()
    if non_null.is_empty():
        return []
    return non_null.unique().sort().head(limit).cast(pl.String).to_list()


def _range_values(series: pl.Series, col_type: str) -> list:
    lo, hi = series.min(), series.max()
    if col_type in ("date", "datetime"):
        lo = lo.isoformat() if lo is not None else None
        hi = hi.isoformat() if hi is not None else None
    return [lo, hi]


def _describe_column(
    df: pl.DataFrame, col: str, key_col: str, redacted_columns: tuple[str, ...] = ()
) -> dict:
    series = df[col]
    col_type = _column_type(series.dtype)
    is_key = bool(key_col) and col == key_col

    column: dict = {"name": col}

    if is_key and col_type == "number":
        column["type"] = "number(id)"
    else:
        column["type"] = col_type

    if col in redacted_columns:
        column["description"] = "Redacted (PII)"

    if is_key:
        column["constraints"] = ["primary_key"]

    if col_type == "boolean":
        return column

    n_unique = series.n_unique()
    if col_type in ("number", "date", "datetime"):
        column["range"] = _range_values(series, col_type)
    elif 0 < n_unique <= _ENUM_MAX_UNIQUE and n_unique < df.height:
        column["type"] = "enum"
        column["values"] = _sample_values(series, _ENUM_MAX_UNIQUE)
    else:
        column["examples"] = _sample_values(series, 5)

    return column


def generate_data_dict(
    df: pl.DataFrame,
    *,
    table_name: str,
    label: str,
    description: str,
    key_col: str,
    parquet_path: str,
    datasure_version: str,
    redacted_columns: tuple[str, ...] = (),
) -> str:
    """Generate a data-dict.yaml compliant data dictionary from a DataFrame.

    Parameters
    ----------
    df : pl.DataFrame
        The dataset to describe (typically the corrected dataset).
    table_name : str
        Machine-readable name for the table (and top-level ``name``).
    label : str
        Human-readable dataset/table title.
    description : str
        Short summary of the dataset.
    key_col : str
        The survey key column name; marked with a ``primary_key`` constraint.
    parquet_path : str
        Path to the Parquet file, relative to the yaml file's location.
    datasure_version : str
        Version of DataSure that generated this file (used in a comment).
    redacted_columns : tuple[str, ...]
        Columns whose values were masked for PII; annotated with a
        "Redacted (PII)" description.

    Returns
    -------
    str
        YAML content as a string.
    """
    today = date.today().isoformat()

    columns = (
        [_describe_column(df, col, key_col, redacted_columns) for col in df.columns]
        if not df.is_empty()
        else []
    )

    doc = {
        "$version": _SPEC_VERSION,
        "$learn_more": _LEARN_MORE,
        "name": table_name,
        "label": label,
        "description": description,
        "version": {"date": today},
        "tables": [
            {
                "name": table_name,
                "label": label,
                "description": description,
                "source": {"parquet": parquet_path},
                "columns": columns,
            }
        ],
    }

    header = (
        f"# Generated by DataSure {datasure_version} on {today}\n"
        f"# Spec: {_LEARN_MORE}\n"
    )
    return header + yaml.safe_dump(
        doc, sort_keys=False, allow_unicode=True, default_flow_style=False
    )
