"""Python script generators for replication packages.

Mirrors ``script_generators.py`` (the Stata do-file generators) but emits
standalone Python/Polars scripts instead. Every generated script carries a
PEP 723 inline-metadata header, so it is independently runnable via
``uv run <script>.py`` — uv reads the header and provisions an ephemeral
virtual environment automatically. There is no Python equivalent of
``1_install_packages.do``: that is the entire point of inline metadata.
"""

from __future__ import annotations

from datetime import date

import polars as pl

from datasure.replication.script_generators import _is_numeric

SCRIPT_EXT_PY = "py"


# ── Shared utilities ──────────────────────────────────────────────────────────


def _py_header(
    title: str,
    project_name: str,
    survey_name: str,
    datasure_version: str,
    dependencies: list[str],
) -> str:
    today = date.today().isoformat()
    sep = "=" * 60
    deps_block = "\n".join(f'#     "{dep}",' for dep in dependencies)
    return "\n".join(
        [
            "# /// script",
            '# requires-python = ">=3.11"',
            "# dependencies = [",
            deps_block,
            "# ]",
            "# ///",
            "#",
            f"# {sep}",
            f"# {title}",
            f"# Project: {project_name}",
            f"# Survey:  {survey_name}",
            f"# Generated by DataSure {datasure_version} on {today}",
            "# No separate package-install step is needed: `uv run` installs",
            "# the dependencies declared above into an ephemeral environment.",
            f"# {sep}",
            "",
        ]
    )


def _safe_survey(survey_name: str) -> str:
    return survey_name.lower().replace(" ", "_")


# ── Corrections helpers ───────────────────────────────────────────────────────


def _py_lit(value: str | None) -> str:
    """Render a correction-log value as a Python literal.

    Numeric-looking strings are emitted as numbers (matching the target
    column's likely dtype); everything else is emitted as a quoted string.
    """
    if value is None:
        return "None"
    if _is_numeric(value):
        num = float(value)
        return repr(int(num)) if num.is_integer() else repr(num)
    return repr(value)


def _emit_py(
    action: str,
    key_col: str,
    key_val: str,
    col: str | None,
    new_val: str | None,
    reason: str,
) -> list[str]:
    comment = f"# {action}: {key_col}=={key_val!r}"
    if col:
        comment += f" | {col}"
    if reason:
        comment += f" | {reason}"

    if action == "modify value" and col and new_val is not None:
        stmt = (
            f"df = df.with_columns(pl.when(pl.col({key_col!r}) == {key_val!r})"
            f".then(pl.lit({_py_lit(new_val)})).otherwise(pl.col({col!r}))"
            f".alias({col!r}))"
        )
    elif action == "remove value" and col:
        stmt = (
            f"df = df.with_columns(pl.when(pl.col({key_col!r}) == {key_val!r})"
            f".then(None).otherwise(pl.col({col!r})).alias({col!r}))"
        )
    elif action == "remove row":
        stmt = f"df = df.filter(pl.col({key_col!r}) != {key_val!r})"
    else:
        return []

    return [comment, stmt, ""]


# ── Public API ────────────────────────────────────────────────────────────────


def generate_corrections_script_py(
    correction_log: pl.DataFrame,
    key_col: str,
    project_name: str,
    survey_name: str,
    datasure_version: str,
) -> str:
    """Generate a Python corrections script from the correction log.

    Parameters
    ----------
    correction_log : pl.DataFrame
        Correction log with columns: action, KEY, column, new_value, reason.
    key_col : str
        The survey key column name.
    project_name : str
        Human-readable project name.
    survey_name : str
        Human-readable survey name.
    datasure_version : str
        Version of DataSure that generated this package.

    Returns
    -------
    str
        Python script content as a string.
    """
    header = _py_header(
        "Corrections Script (Python)",
        project_name,
        survey_name,
        datasure_version,
        ["polars"],
    )
    safe_survey = _safe_survey(survey_name)

    preamble = [
        header,
        "from pathlib import Path",
        "",
        "import polars as pl",
        "",
        "PKG_ROOT = Path(__file__).resolve().parents[1]",
        f'PREPPED = PKG_ROOT / "3_data" / "2_intermediate" / "{safe_survey}_prepped.parquet"',
        f'OUT = PKG_ROOT / "3_data" / "3_final" / "{safe_survey}_corrected.parquet"',
        "",
        "df = pl.read_parquet(PREPPED)",
        "",
    ]

    if not key_col:
        lines = [
            *preamble,
            "# WARNING: no key column configured — corrections script is a no-op.",
        ]
    elif correction_log.is_empty():
        lines = [*preamble, "# No corrections recorded."]
    else:
        lines = preamble
        for row in correction_log.iter_rows(named=True):
            action = str(row.get("action") or "")
            key_val = str(row.get("KEY") or "")
            col = row.get("column")
            new_val = row.get("new_value")
            reason = str(row.get("reason") or "")
            lines += _emit_py(action, key_col, key_val, col, new_val, reason)

    lines += ["df.write_parquet(OUT)", 'print(f"Wrote {OUT} — {df.height:,} rows")']
    return "\n".join(lines) + "\n"


def generate_deidentify_script_py(
    pii_flags: pl.DataFrame,
    project_name: str,
    survey_name: str,
    datasure_version: str,
) -> str:
    """Generate a Python script that de-identifies the bundled datasets.

    Included in packages exported *with* PII: it encodes the PII decisions
    recorded in DataSure (mask/drop per column; undecided treated as mask)
    so a recipient can produce de-identified copies of every bundled
    Parquet dataset with ``uv run 5_deidentify_data.py``.

    Parameters
    ----------
    pii_flags : pl.DataFrame
        PII flags table (processing/pii.py canonical schema).
    project_name : str
        Human-readable project name.
    survey_name : str
        Human-readable survey name.
    datasure_version : str
        Version of DataSure that generated this package.

    Returns
    -------
    str
        Python script content as a string.
    """
    header = _py_header(
        "De-identification Script (Python)",
        project_name,
        survey_name,
        datasure_version,
        ["polars"],
    )
    safe_survey = _safe_survey(survey_name)

    decisions: list[tuple[str, str, str]] = []
    for row in pii_flags.iter_rows(named=True):
        decision = row["decision"]
        if decision == "undecided":
            decision = "mask"  # conservative default
        if decision in ("mask", "drop"):
            decisions.append((row["column"], decision, row["mask_label"] or "*****"))

    decision_lines = (
        ["DECISIONS = ["] + [f"    {d!r}," for d in decisions] + ["]"]
        if decisions
        else ["DECISIONS = []  # no PII flags were recorded in DataSure"]
    )

    lines = [
        header,
        "from pathlib import Path",
        "",
        "import polars as pl",
        "",
        "PKG_ROOT = Path(__file__).resolve().parents[1]",
        "DATASETS = [",
        f'    PKG_ROOT / "3_data" / "1_raw" / "{safe_survey}_raw.parquet",',
        f'    PKG_ROOT / "3_data" / "2_intermediate" / "{safe_survey}_prepped.parquet",',
        f'    PKG_ROOT / "3_data" / "3_final" / "{safe_survey}_corrected.parquet",',
        "]",
        "",
        "# (column, action, mask_label) decisions recorded in DataSure's PII",
        '# review. "mask" replaces every non-null value with the label;',
        '# "drop" removes the column.',
        *decision_lines,
        "",
        "for path in DATASETS:",
        "    if not path.exists():",
        "        continue",
        "    df = pl.read_parquet(path)",
        "    for column, action, label in DECISIONS:",
        "        if column not in df.columns:",
        "            continue",
        '        if action == "drop":',
        "            df = df.drop(column)",
        "        else:",
        "            df = df.with_columns(",
        "                pl.when(pl.col(column).is_not_null())",
        "                .then(pl.lit(label))",
        "                .otherwise(pl.lit(None, dtype=pl.String))",
        "                .alias(column)",
        "            )",
        '    out = path.with_name(path.stem + "_deidentified.parquet")',
        "    df.write_parquet(out)",
        '    print(f"Wrote {out} — {df.height:,} rows")',
        "",
        'print("")',
        'print("WARNING: De-identification is not anonymization. Even with")',
        'print("direct identifiers masked or dropped, subjects may remain")',
        'print("identifiable through combinations of remaining variables")',
        'print("(e.g. age, location, occupation). Review before sharing.")',
    ]
    return "\n".join(lines) + "\n"


def generate_master_script_py(
    project_name: str,
    survey_name: str,
    datasure_version: str,
) -> str:
    """Generate the Python master replication script.

    Parameters
    ----------
    project_name : str
        Human-readable project name.
    survey_name : str
        Human-readable survey name.
    datasure_version : str
        Version of DataSure.

    Returns
    -------
    str
        Python script content as a string.
    """
    header = _py_header(
        "Master Replication Script (Python)",
        project_name,
        survey_name,
        datasure_version,
        ["polars"],
    )

    lines = [
        header,
        "import subprocess",
        "from pathlib import Path",
        "",
        "# -------------------------------------------------------",
        "# No manual path configuration needed: every script locates the",
        "# package root relative to its own file location.",
        "# Run with:      uv run 0_main.py",
        "# Each step is also independently runnable on its own, e.g.:",
        "#                uv run 4_corrections.py",
        "#",
        "# Steps are invoked via `uv run` (not the current interpreter) so",
        "# each step's own PEP 723 inline dependencies are honored, even if a",
        "# future step declares packages beyond what this master script needs.",
        "#",
        "# There is no 2_import_data.py: the raw dataset is already bundled as",
        "# a Parquet file (3_data/1_raw/*_raw.parquet) with the real dtypes",
        "# DataSure resolved on import, so 3_prepare_data.py reads it directly",
        "# instead of re-deriving types from the CSV (that's only needed on",
        "# the Stata side, since Stata can't read Parquet).",
        "# -------------------------------------------------------",
        "",
        "SCRIPTS_DIR = Path(__file__).resolve().parent",
        "STEPS = [",
        '    "3_prepare_data.py",',
        '    "4_corrections.py",',
        "]",
        "",
        "for step in STEPS:",
        '    print(f"--- Running {step} ---")',
        '    subprocess.run(["uv", "run", str(SCRIPTS_DIR / step)], check=True)',
        "",
        'print("Done. Datasets written to 3_data/2_intermediate/ and 3_data/3_final/.")',
    ]
    return "\n".join(lines) + "\n"
