"""Stata script generators for replication packages."""

from __future__ import annotations

from datetime import date

import polars as pl

SCRIPT_EXT = "do"
_C = "*"  # Stata comment character
_LOG_CLOSE = "cap log close"


# ── Shared utilities ──────────────────────────────────────────────────────────


def _header(
    title: str,
    project_name: str,
    survey_name: str,
    datasure_version: str,
) -> str:
    today = date.today().isoformat()
    sep = "=" * 60
    return "\n".join(
        [
            f"{_C} {sep}",
            f"{_C} {title}",
            f"{_C} Project: {project_name}",
            f"{_C} Survey:  {survey_name}",
            f"{_C} Generated by DataSure {datasure_version} on {today}",
            f"{_C} {sep}",
            "",
        ]
    )


# ── Corrections helpers ───────────────────────────────────────────────────────


def _escape(value: str) -> str:
    """Escape double quotes in a Stata string literal."""
    return value.replace('"', '""')


def _is_numeric(value: str) -> bool:
    try:
        float(value)
    except (ValueError, TypeError):
        return False
    else:
        return True


def _emit_stata(
    action: str,
    key_col: str,
    key_val: str,
    col: str | None,
    new_val: str | None,
    reason: str,
) -> list[str]:
    comment = f"{_C} {action}: {key_col}=={key_val!r}"
    if col:
        comment += f" | {col}"
    if reason:
        comment += f" | {reason}"

    escaped_key = _escape(key_val)

    if action == "modify value" and col and new_val is not None:
        if _is_numeric(new_val):
            stmt = f'replace {col} = {new_val} if {key_col} == "{escaped_key}"'
        else:
            escaped_val = _escape(new_val)
            stmt = f'replace {col} = "{escaped_val}" if {key_col} == "{escaped_key}"'
    elif action == "remove value" and col:
        stmt = f'replace {col} = . if {key_col} == "{escaped_key}"'
    elif action == "remove row":
        stmt = f'drop if {key_col} == "{escaped_key}"'
    else:
        return []

    return [comment, stmt, ""]


# ── Public API (in execution order: master → install → import → corrections) ──


def generate_master_script(
    project_name: str,
    survey_name: str,
    datasure_version: str,
) -> str:
    """Generate the Stata master replication script.

    Parameters
    ----------
    project_name : str
        Human-readable project name.
    survey_name : str
        Human-readable survey name.
    datasure_version : str
        Version of DataSure.

    Returns
    -------
    str
        Stata script content as a string.
    """
    header = _header(
        "Master Replication Script",
        project_name,
        survey_name,
        datasure_version,
    )
    safe_survey = survey_name.lower().replace(" ", "_")
    safe_project = project_name.lower().replace(" ", "_")

    lines = [
        header,
        "* -------------------------------------------------------",
        "* INSTRUCTIONS:",
        "* 1. Set `root` below to the full path of the parent folder",
        f"*    that contains the replication_{safe_project}_{safe_survey}/ directory.",
        "*    Example:  global root C:/Users/you/Desktop",
        "* 2. Run this script from the Stata command window:",
        "*    do 0_main.do",
        "* -------------------------------------------------------",
        "",
        "cls",
        "clear all",
        "set trace off",
        "set more off",
        "",
        'global root    "REPLACE_WITH_PARENT_PATH"',
        f'global pkg     "$root/replication_{safe_project}_{safe_survey}"',
        'global scripts "$pkg/2_scripts"',
        'global docs    "$pkg/1_docs"',
        'global raw     "$pkg/3_data/1_raw"',
        'global inter   "$pkg/3_data/2_intermediate"',
        'global final   "$pkg/3_data/3_final"',
        'global output  "$pkg/4_output"',
        'global logs    "$output/3_logs"',
        'global tables  "$output/1_tables"',
        'global figures "$output/2_figures"',
        "",
        "* Create date-based log subfolder and start run log",
        'local datestr = string(date(c(current_date), "DMY"), "%tdCCYY-NN-DD")',
        'global logdir "$logs/`datestr\'"',
        'cap mkdir "$logdir"',
        "cap log close",
        'log using "$logdir/0_main.log", replace text',
        "",
        "* Step 1: Install required packages",
        'do "$scripts/1_install_packages.do"',
        "",
        "* Step 2: Import raw CSV and save as Stata dataset",
        'do "$scripts/2_import_data.do"',
        "",
        "* Step 3: Apply preparation steps",
        f'use "$raw/{safe_survey}_raw.dta", clear',
        'do "$scripts/3_prepare_data.do"',
        "",
        "* Save prepped dataset",
        f'save "$inter/{safe_survey}_prepped.dta", replace',
        "",
        "* Step 4: Apply all recorded corrections",
        'do "$scripts/4_corrections.do"',
        "",
        "* Save corrected dataset",
        f'save "$final/{safe_survey}_corrected.dta", replace',
        "",
        "* Step 5: Generate codebook (requires ipaclean)",
        'ipacodebook using "$docs/2_codebooks/codebook.xlsx", replace',
        "",
        "log close",
        'display "Done. Datasets saved to 3_data/ and codebook to 1_docs/2_codebooks/."',
    ]

    return "\n".join(lines) + "\n"


def generate_install_packages_script(
    project_name: str,
    survey_name: str,
    datasure_version: str,
) -> str:
    """Generate a Stata do-file that installs all required packages.

    Parameters
    ----------
    project_name : str
        Human-readable project name.
    survey_name : str
        Human-readable survey name.
    datasure_version : str
        Version of DataSure.

    Returns
    -------
    str
        Stata script content as a string.
    """
    header = _header("Install Packages", project_name, survey_name, datasure_version)

    lines = [
        header,
        'cap log using "$logdir/1_install_packages.log", replace text',
        "",
        "* Install github package manager",
        'net install github, from("https://haghish.github.io/github/")',
        "",
        "* Install IPA packages",
        "github install PovertyAction/high-frequency-checks",
        "github install PovertyAction/ipahelper",
        "github install PovertyAction/ipaclean",
        "github install PovertyAction/ipaplots",
        "",
        'display "All packages installed."',
        "",
        _LOG_CLOSE,
    ]

    return "\n".join(lines) + "\n"


def generate_import_script(
    project_name: str,
    survey_name: str,
    datasure_version: str,
) -> str:
    """Generate a Stata import script that loads the raw CSV and saves as DTA.

    Parameters
    ----------
    project_name : str
        Human-readable project name.
    survey_name : str
        Human-readable survey name.
    datasure_version : str
        Version of DataSure.

    Returns
    -------
    str
        Stata script content as a string.
    """
    header = _header("Import Script", project_name, survey_name, datasure_version)
    safe_survey = survey_name.lower().replace(" ", "_")

    lines = [
        header,
        'cap log using "$logdir/2_import_data.log", replace text',
        "",
        "* Import raw CSV dataset (all columns as strings to preserve data as-is)",
        f'import delimited "$raw/{safe_survey}_raw.csv", stringcols(_all) clear',
        "",
        "* Save as Stata dataset",
        f'save "$raw/{safe_survey}_raw.dta", replace',
        "",
        'display "Raw dataset imported and saved as DTA."',
        "",
        _LOG_CLOSE,
    ]
    return "\n".join(lines) + "\n"


def generate_corrections_script(
    correction_log: pl.DataFrame,
    key_col: str,
    project_name: str,
    survey_name: str,
    datasure_version: str,
) -> str:
    """Generate a Stata corrections script from the correction log.

    Parameters
    ----------
    correction_log : pl.DataFrame
        Correction log with columns: action, KEY, column, new_value, reason.
    key_col : str
        The survey key column name.
    project_name : str
        Human-readable project name.
    survey_name : str
        Human-readable survey name.
    datasure_version : str
        Version of DataSure that generated this package.

    Returns
    -------
    str
        Stata script content as a string.
    """
    header = _header("Corrections Script", project_name, survey_name, datasure_version)

    if not key_col:
        return (
            header
            + 'cap log using "$logdir/4_corrections.log", replace text\n'
            + f"{_C} WARNING: no key column configured — corrections script is empty.\n"
            + _LOG_CLOSE
            + "\n"
        )

    if correction_log.is_empty():
        return (
            header
            + 'cap log using "$logdir/4_corrections.log", replace text\n'
            + f"{_C} No corrections recorded.\n"
            + _LOG_CLOSE
            + "\n"
        )

    lines: list[str] = [
        header,
        'cap log using "$logdir/4_corrections.log", replace text',
        "",
    ]

    for row in correction_log.iter_rows(named=True):
        action = str(row["action"])
        key_val = str(row["KEY"])
        col = row.get("column")
        new_val = row.get("new_value")
        reason = str(row.get("reason") or "")
        lines += _emit_stata(action, key_col, key_val, col, new_val, reason)

    lines.append(_LOG_CLOSE)
    return "\n".join(lines)
