[theme]

# use light theme as base
base = "light"

# Primary accent color for interactive elements
# primaryColor = "#6eb52f"

# Background color for the main content area
backgroundColor = "#FAF9F6"

# Background color used for the sidebar and most interactive widgets
# secondaryBackgroundColor = "#84d0d4"

# Color used for almost all text
# textColor = "#262730"


[client]
toolbarMode = "minimal"


[server]

# maximum amount of data in MB that can be handled by streamlit, default is 200
maxMessageSize = 1000
maxUploadSize = 1000

# Number of seconds of inactivity before session state is reset, default is 120
disconnectedSessionTTL = 480